export const DATALIST =  {
    'Feather' : 'img/dog.png',
    '3DBio' : 'img/phone.jpg',
    'Mobalytics' :'img/dog.png',
    'Holo|one' :'img/phone.jpg',
    'Patreon' : 'img/dog.png',
    'Aria Pharmaceuticals' : 'img/phone.jpg',
    'Spin': 'img/dog.png',
    'Speedsize' : 'img/phone.jpg',
    'Prive' : 'img/dog.png',
    'Muncher' : 'img/phone.jpg',
    'CubiOs' : 'img/dog.png',
    '8base' : 'img/phone.jpg',
    'Pinscreen' : 'img/dog.png',
    'Vyng' : 'img/phone.jpg',
    'Adway': 'img/dog.png',
    'Accern': 'img/phone.jpg',
    'Volumetric*': 'img/dog.png',
    'Instreamic': 'img/phone.jpg',
    '3DLook': 'img/dog.png',
    'Respeecher': 'img/dog.png',
    'Hypoint': 'img/phone.jpg',
    'Racoon.Recovery': 'img/dog.png',
  
  }
